const data = [
  {
    id: 1,
    image: 'product_05-',
    name: 'Caine Chair',
    about: 'descrition about this product...',
    oldPrice: null,
    newPrice: '100$',
    sale: false,
    new: false,
    category: 'Chair, Wooden',
    brand: 'Baker',
  },
  {
    id: 2,
    image: 'product_14-',
    about: 'descrition about this product...',
    name: 'Casual Chair (Robo)',
    oldPrice: null,
    newPrice: '200$',
    sale: false,
    new: false,
    category: 'Chair, Wooden',
    brand: 'Baker',
  },
  {
    id: 3,
    image: 'product_08-',
    about: 'descrition about this product...',
    name: 'Decorator Chair',
    oldPrice: null,
    newPrice: '150$',
    sale: false,
    new: false,
    category: 'Chair, Wooden',
    brand: 'Baker',
  },
  {
    id: 4,
    image: 'product_12-',
    about: 'descrition about this product...',
    name: 'Delux Wardrobe (3 Drawer)',
    oldPrice: null,
    newPrice: '2000$',
    sale: false,
    new: false,
    category: 'Wardrobe',
    brand: 'Baker',
  },
  {
    id: 5,
    image: 'product_13-',
    about: 'descrition about this product......',
    name: 'Delux Wardrobe (5 Drawer)',
    oldPrice: null,
    newPrice: '100$',
    sale: false,
    new: false,
    category: 'Chair, Wooden',
    brand: 'Baker',
  },
  {
    id: 6,
    image: 'product_09-',
    about: 'descrition about this product...',
    name: 'Dining Table',
    oldPrice: '100$',
    newPrice: '69$',
    sale: false,
    new: false,
    category: 'Chair, Wooden',
    brand: 'Baker',
  },
  {
    id: 7,
    image: 'product_11-',
    about: 'descrition about this product...',
    name: 'Delux Wardrobe (4 Drawer)',
    oldPrice: '250$',
    newPrice: '122$',
    sale: false,
    new: false,
    category: 'Chair, Wooden',
    brand: 'Baker',
  },
  {
    id: 8,
    image: 'product_13-',
    about: 'descrition about this product...',
    name: 'Delux Wardrobe (5 Drawer)',
    oldPrice: null,
    newPrice: '100$',
    sale: false,
    new: false,
    category: 'Chair, Wooden',
    brand: 'Baker',
  },
  {
    id: 9,
    image: 'product_01-',
    about: 'descrition about this product...',
    name: 'Laoreet Congue',
    oldPrice: '350$',
    newPrice: '260$',
    sale: false,
    new: false,
    category: 'Chair, Wooden',
    brand: 'Baker',
  },
  {
    id: 10,
    image: 'product_17-',
    about: 'descrition about this product...',
    name: 'Delux Unitaz',
    oldPrice: null,
    newPrice: '300$',
    sale: false,
    new: false,
    category: 'Chair, Wooden',
    brand: 'Baker',
  },
  {
    id: 11,
    image: 'product_03-',
    about: 'descrition about this product...',
    name: 'Delux Wardrobe (5 Drawer)',
    oldPrice: null,
    newPrice: '100$',
    sale: false,
    new: false,
    category: 'Chair, Wooden',
    brand: 'Baker',
  },
  {
    id: 12,
    image: 'product_02-',
    about: 'descrition about this product...',
    name: 'Laoreet Congue',
    oldPrice: '350$',
    newPrice: '260$',
    sale: false,
    new: false,
    category: 'Chair, Wooden',
    brand: 'Baker',
  },
];

export default data;
